name: Telegram Notification on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.3
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            💡 A new push event occurred in the repository:
            Repository: ${{ github.repository }}
            Commit message: ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
            [View changes](${{ github.event.head_commit.url }})
